project_id = "crllgygjuqpluvdpwayi"

[functions.google-form-webhook]
verify_jwt = false

[functions.send-course-reminders]
verify_jwt = false

[functions.cocreation-refine-response]
verify_jwt = false
