
# Netlify configuration file
[build]
  command = "npm run build"
  publish = "dist"

# Ensure SPA routing works for all paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
# Enable different configurations for main domain and app subdomain
[context.production]
  environment = { NODE_ENV = "production" }

[context.production.environment]
  VITE_APP_URL = "https://limitlesslab.org"
